apiVersion:  extensions/v1beta1
kind: Deployment
metadata:
  name: tap-estry-deployment
  labels:
    app: tap-estry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tap-estry
  template:
    metadata:
      labels:
        app: front-end-pod
    spec:
      containers:
      - name: front-end
        image: eu.gcr.io/tap-estry-186513/tap-estry
        ports:
         - containerPort: 8080