apiVersion: v1
kind: Service
metadata:
  labels:
    app: tap-estry-service
  name: tap-estry-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tap-estry-pod
  sessionAffinity: None
  type: LoadBalancer
