apiVersion: v1
kind: Service
metadata:
  labels:
    app: tap-estry-service
  name: tap-estry-service
spec:
#  clusterIP: 10.55.255.116
#  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front-end-pod
  sessionAffinity: None
  type: LoadBalancer
