package database;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@Controller
public class StorageController {
    @Autowired //bean is called onto the storage repository to allow access -- auto generated by spring
    private StorageRepository storageRepository;

    public void addNewStorageDetails (String image_location, Integer[] pixel_size, List<Integer> colours){
        Storage storage = new Storage();
        System.out.println("did it get to here");
        storage.setColours(colours);
        storage.setImage_Location(image_location);
        storage.setPixelSize(pixel_size);
    }

}
